#!/bin/bash
# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
set -e

WORKING_DIR="/tmp/webapp"
BUILD_DIR="$WORKING_DIR/build"
PATCH_CONFIG_DIR="/webapp/patch_config"
CONFIG_FILE="$PATCH_CONFIG_DIR/config/apis.json"
OUTPUT_JS="$BUILD_DIR/config/publicWebappConfig.js"

echo "Copying webapp build folder to $BUILD_DIR..."
cp -r /usr/share/nginx/html "$BUILD_DIR"

# Generate window.publicWebappConfig JS file from ConfigMap-mounted apis.json
if [ -f "$CONFIG_FILE" ]; then
  echo "Found config file: $CONFIG_FILE"
  mkdir -p "$BUILD_DIR/config"

  APIS_CONTENT=$(cat "$CONFIG_FILE")
  cat > "$OUTPUT_JS" <<EOF
// Auto-generated by patch_and_start_server.sh — do not edit
window.publicWebappConfig = {
  APIS: $APIS_CONTENT
};
EOF
  echo "Generated $OUTPUT_JS"

  # Patch index.html to load the generated config script
  INDEX_FILE="$BUILD_DIR/index.html"
  if [ -f "$INDEX_FILE" ]; then
    sed -i 's|<script id="publicWebappConfigElement"></script>|<script src="/config/publicWebappConfig.js"></script>|g' "$INDEX_FILE"
    echo "Patched $INDEX_FILE with publicWebappConfig script tag"
  else
    echo "WARNING: $INDEX_FILE not found, skipping patch"
  fi
else
  echo "No config file found at $CONFIG_FILE, using build-time defaults"
fi

# Replace nginx default html with patched build
#rm -rf /usr/share/nginx/html
#ln -s "$BUILD_DIR" /usr/share/nginx/html
rm -rf /usr/share/nginx/html/*
cp -r "$BUILD_DIR"/. /usr/share/nginx/html/

echo "Starting nginx..."
exec nginx -g "daemon off;"
