#!/bin/bash
# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
set -e

# 1. Configuration des dossiers
WORKING_DIR="/tmp/webapp"
BUILD_DIR="$WORKING_DIR/build"
PATCH_CONFIG_DIR="/webapp/patch_config"
CONFIG_FILE="$PATCH_CONFIG_DIR/config/apis.json"
OUTPUT_JS="$BUILD_DIR/config/publicWebappConfig.js"
INDEX_FILE="$BUILD_DIR/index.html"

echo "Copying webapp build folder to $BUILD_DIR..."
# On copie les fichiers vers un dossier temporaire car le dossier d'origine est souvent en lecture seule
mkdir -p "$BUILD_DIR"
cp -r /usr/share/nginx/html/. "$BUILD_DIR"

# 2. Génération de la configuration dynamique
if [ -f "$CONFIG_FILE" ]; then
  echo "Found config file: $CONFIG_FILE. Generating $OUTPUT_JS..."
  mkdir -p "$BUILD_DIR/config"

  APIS_CONTENT=$(cat "$CONFIG_FILE")
  
  # On crée le fichier JS qui sera lu par l'application au démarrage
  cat > "$OUTPUT_JS" <<EOF
// Auto-generated by patch_and_start_server.sh — do not edit
window.publicWebappConfig = {
  APIS: $APIS_CONTENT
};
EOF

  # 3. Patch du fichier index.html
  if [ -f "$INDEX_FILE" ]; then
    # CORRECTION : On utilise "./config/..." (relatif) au lieu de "/config/..." (absolu)
    # Cela permet à l'Ingress /admin-portal de trouver le fichier correctement.
    sed -i 's|<script id="publicWebappConfigElement"></script>|<script src="./config/publicWebappConfig.js"></script>|g' "$INDEX_FILE"
    echo "Successfully patched $INDEX_FILE with relative config path."
  else
    echo "WARNING: $INDEX_FILE not found, skipping patch."
  fi
else
  echo "No config file found at $CONFIG_FILE, using build-time defaults."
fi

# 4. Lancement de Nginx
echo "Starting nginx..."
exec nginx -g "daemon off;"