#!/bin/bash
# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
#
# This script patches the Vite build output at container startup:
#   1. Generates publicWebappConfig.js from the ConfigMap-mounted apis.json
#   2. Rewrites all absolute asset paths in index.html with the PUBLIC_URL prefix
#      so that the nginx-ingress rewrite rule can route them correctly.
#
# Approach matches the reference Cosmo Tech webapp server (azure-sample-webapp).
set -e

WORKING_DIR="/tmp/webapp"
BUILD_DIR="$WORKING_DIR/build"
PATCH_CONFIG_DIR="/webapp/patch_config"
CONFIG_FILE="$PATCH_CONFIG_DIR/config/apis.json"
# Place the config JS in assets/ (same folder Vite uses for hashed bundles)
OUTPUT_JS="$BUILD_DIR/assets/publicWebappConfig.js"
INDEX_FILE="$BUILD_DIR/index.html"
PUBLIC_URL="${PUBLIC_URL:-}"

echo "Copying webapp build folder to $BUILD_DIR..."
mkdir -p "$BUILD_DIR"
cp -r /usr/share/nginx/html/. "$BUILD_DIR"

if [ -f "$CONFIG_FILE" ]; then
  echo "Found config file: $CONFIG_FILE"
  mkdir -p "$BUILD_DIR/assets"

  APIS_CONTENT=$(cat "$CONFIG_FILE")

  # Generate the runtime config JS that the app reads on startup
  cat > "$OUTPUT_JS" <<EOF
// Auto-generated by patch_and_start_server.sh — do not edit
window.publicWebappConfig = {
  PUBLIC_URL: "$PUBLIC_URL",
  APIS: $APIS_CONTENT
};
EOF
  echo "Generated $OUTPUT_JS"

  if [ -f "$INDEX_FILE" ]; then
    # Step 1: Insert the config script tag (absolute path — will be prefixed below)
    sed -i 's|<script id="publicWebappConfigElement"></script>|<script src="/assets/publicWebappConfig.js"></script>|g' "$INDEX_FILE"
    echo "Inserted publicWebappConfig.js script tag"

    # Step 2: Rewrite ALL absolute paths so the browser requests go through the
    #         ingress sub-path.  e.g. src="/assets/x.js" → src="/admin-portal/assets/x.js"
    #         This is the same approach used by the azure-sample-webapp reference repo.
    if [ -n "$PUBLIC_URL" ]; then
      PREFIX="${PUBLIC_URL%/}"  # strip trailing slash
      sed -i "s|=\"/|=\"${PREFIX}/|g" "$INDEX_FILE"
      echo "Rewrote absolute paths in index.html with prefix '$PREFIX'"
    fi
  else
    echo "WARNING: $INDEX_FILE not found, skipping patch"
  fi
else
  echo "No config file found at $CONFIG_FILE, using build-time defaults"
fi

echo "Starting nginx..."
exec nginx -g "daemon off;"