version = 1


[[annotations]]
path = [
  "**/*.json",
  "**/*.ico",
  "yarn.lock",
]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024-2025 Cosmo Tech"
SPDX-License-Identifier = "LicenseRef-CosmoTech"
